openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/662781/BankAPI/1.3
info:
  description: This is a Bank API
  version: "1.3"
  title: Bank API
  contact:
    email: 662781@student.inholland.nl
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: Employee
    description: Operations available to employees
  - name: Customer
    description: Operations available to customers
security:
  - bearerAuth: []
paths:
  /login:
    post:
      security: []
      tags:
        - Employee
        - Customer
      summary: User Login
      operationId: login
      requestBody:
        description: Object with username and password to compare to existing data in DB
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginDTO"
      responses:
        200:
          description: User login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenDTO"
        401:
          description: Request not authorized - Access token is missing or invalid
  /users:
    post:
      security: []
      tags:
        - Customer
      summary: Register User Data
      operationId: addUser
      requestBody:
        description: New user object
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDTO"
      responses:
        201:
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
        400:
          description: Invalid user object
    get:
      description: |
        By passing in the appropriate options, you can search for
        users in the DB
      parameters:
        - in: query
          name: skip
          description: Number of records to skip for pagination
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: limit
          description: Maximum number of records to return
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 200000
      tags:
        - Employee
      summary: Search a user list with pagination
      operationId: getAllUsers
      responses:
        200:
          description: Users found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserDTO"
        404:
          description: No users found
  /users/getByEmail/{email}:
    parameters:
      - in: path
        name: email
        required: true
        description: Email input
        schema:
          type: string
          format: email
    get:
      tags:
        - Employee
      summary: Search a user list on email address
      operationId: getByEmail
      responses:
        200:
          description: User found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
        404:
          description: User not found
  /users/getByUsername/{username}:
    parameters:
      - in: path
        name: username
        required: true
        description: Username input
        schema:
          type: string
    get:
      tags:
        - Employee
      summary: Search a user list on username
      operationId: getByUsername
      responses:
        200:
          description: User found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
        404:
          description: User not found
    put:
      tags:
        - Employee
        - Customer
      summary: Updates a user
      operationId: updateUser
      description: |
        By sending this request, an employee or customer can update the information of one user
      requestBody:
        description: Updated user object
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDTO"
      responses:
        200:
          description: User found and updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
        404:
          description: User not found
  /users/getAllWithoutAccount:
    get:
      tags:
        - Employee
      summary: Find all user without an account
      operationId: getAllUsersWithoutAccount
      responses:
        200:
          description: Users found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserDTO"
        404:
          description: All users have an account or user not found
  /accounts:
    get:
      tags:
        - Employee
      summary: Search account list with pagination
      operationId: getAccounts
      description: |
        By passing in the appropriate options, you can search for
        accounts in the DB
      parameters:
        - in: query
          name: skip
          description: Number of records to skip for pagination
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: limit
          description: Maximum number of records to return
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 200000
      responses:
        200:
          description: Search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AccountDTO"
        400:
          description: bad input parameter
    post:
      tags:
        - Employee
      summary: Add a new bank account
      operationId: addAccount
      requestBody:
        description: New account object
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountDTO"
      responses:
        201:
          description: Account created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountDTO"
        400:
          description: Invalid account object
  /accounts/getByUserID/{userID}:
    parameters:
      - in: path
        name: userID
        required: true
        description: User ID input
        schema:
          type: string
          format: uuid
    get:
      tags:
        - Employee
        - Customer
      summary: Search an account list on UserID
      operationId: getAccountsByOwnerID
      responses:
        200:
          description: Accounts found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AccountDTO"
        404:
          description: Account not found
  /accounts/{iban}:
    parameters:
      - in: path
        name: iban
        required: true
        description: IBAN input
        schema:
          type: string
    get:
      tags:
        - Employee
        - Customer
      summary: Search an account list on IBAN
      operationId: getAccountByIban
      responses:
        200:
          description: Account found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountDTO"
        404:
          description: Account not found
    put:
      tags:
        - Employee
        - Customer
      summary: Updates an account
      operationId: updateAccount
      description: |
        By sending this request, an employee can update the account information with the given IBAN
      requestBody:
        description: Updated account object
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountDTO"
      responses:
        200:
          description: Account found and updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountDTO"
        404:
          description: Account IBAN not found
  /transactions:
    post:
      tags:
        - Employee
        - Customer
      summary: Create a new transaction
      operationId: createTransaction
      requestBody:
        description: New transaction object
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionDTO"
      responses:
        201:
          description: Transaction created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionDTO"
        400:
          description: Invalid transaction
  /transactions/user:
    get:
      tags:
        - Employee
        - Customer
      summary: Get all transactions for the currently logged-in user
      operationId: getAllUserTransactions
      description: |
        Retrieves all transactions associated with the currently logged-in user.
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: Transactions found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TransactionDTO"
        404:
          description: No transactions found for the user
        401:
          $ref: "#/components/responses/UnauthorizedError"

  /transactions/{id}:
    parameters:
      - in: path
        name: id
        required: true
        description: Transaction ID input
        schema:
          type: string
          format: uuid
    get:
      tags:
        - Employee
        - Customer
      summary: Get one transaction on Id
      operationId: getTransaction
      responses:
        200:
          description: Transaction found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionDTO"
        404:
          description: Transaction not found
    put:
      tags:
        - Employee
        - Customer
      summary: Updates a scheduled transaction
      operationId: updateTransaction
      description: |
        By sending this request, an employee or customer can update a scheduled transaction
      requestBody:
        description: Updated transaction object
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionDTO"
      responses:
        200:
          description: Transaction found and updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionDTO"
        404:
          description: Transaction not found
    delete:
      tags:
        - Employee
        - Customer
      summary: Delete a scheduled transaction
      operationId: deleteTransaction
      responses:
        204:
          description: Scheduled transaction deleted
        404:
          description: Transaction not found
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  schemas:
    LoginDTO:
      description: Object with user login credentials
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: FluffyUnicorn77
        password:
          type: string
          format: password
          minLength: 10
          example: SeCrEt!334
    TokenDTO:
      description: Request body for login responses with JWT
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    UserDTO:
      type: object
      required:
        - username
        - firstname
        - lastname
        - dob
        - address
        - email
        - phone
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        userTypes:
          type: array
          items:
            $ref: "#/components/schemas/UserType"
        username:
          type: string
          example: FluffyUnicorn77
        password:
          type: string
          format: password
          minLength: 10
          example: SeCrEt!334
          writeOnly: true
        firstname:
          type: string
          example: John
        lastname:
          type: string
          example: Doe
        dob:
          type: string
          format: date
          example: "1956-04-24"
        address:
          type: string
          example: Wolkenweg 15 8324AD Haarlem
        email:
          type: string
          example: johndoe@example.com
        phone:
          type: string
          example: +31 0634534565
        registeredOn:
          type: string
          format: date-time
          example: "2022-04-24 12:57:00"
        dayLimit:
          type: number
          format: double
          example: 5000.00
        transLimit:
          type: number
          format: double
          example: 2000.00
        active:
          type: boolean
    UserType:
      type: string
      enum:
        - employee
        - customer
    AccountDTO:
      type: object
      required:
        - accountType
        - balance
        - absLimit
        - active
      properties:
        iban:
          type: string
          example: NLxxINHO0xxxxxxxxx
        accountType:
          $ref: "#/components/schemas/AccountType"
        ownerId:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        pincode:
          type: integer
          example: 1234
        balance:
          type: number
          format: double
          example: 3.21
        absLimit:
          type: number
          format: double
          example: -100
        active:
          type: boolean
    AccountType:
      type: string
      enum:
        - savings
        - current
    TransactionDTO:
      type: object
      required:
        - from
        - to
        - amount
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        transactionType:
          $ref: "#/components/schemas/TransactionType"
        timestamp:
          type: string
          format: date-time
          example: "2022-04-24 12:57:00"
        from:
          type: string
          example: NLxxINHO0xxxxxxxxx
        to:
          type: string
          example: NLxxINHO0xxxxxxxxx
        amount:
          type: number
          format: double
          example: 3.20
          description: Amount of Euros
        userPerforming:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        pincode:
          type: integer
          example: 1234
    TransactionType:
      type: string
      enum:
        - regular
        - deposit
        - withdraw